version: "3.4"

networks:
  xentral:
    driver: bridge

services:
  core:
    hostname: core
    container_name: core
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["yarn", "dev"]
    volumes:
      - .:/home/node/auth_service
      - /home/node/auth_service/node_modules
    ports:
      - "9000:9000"
    networks:
      - starlink
