version: '3.4'

networks:
  starlink:
    driver: bridge

services:
  auth_service:
    hostname: auth_service
    container_name: auth_service
    command: ["yarn", "start"]
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./auth_service/node_modules:/home/node/auth_service/node_modules
      - ./auth_service:/home/node/auth_service
    ports:
      - "5001:5001"
    networks:
      - starlink
